{% set name = "angle-grinder" %}
{% set version = "0.19.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rcoh/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 13ae3912dcc34c2648d8ef57fe8d976cb978c70e6976ead079ea5d7609532172

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - make

test:
  commands:
    - agrind --help

about:
  home: https://github.com/rcoh/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Slice and dice log files on the command-line
  dev_url: https://github.com/rcoh/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
